name: mllf
channels:
  - defaults
dependencies:
  - python==3.10.12
  - pip
  - pip:
    - matplotlib-inline==0.1.6
    - numpy==1.26.4
    - opencv-python==4.9.0.80
    - pandas==2.2.0
    - pillow==10.2.0
    - pip==23.3.1
    - scikit-image==0.22.0
    - scipy==1.12.0
    - torch==2.2.0
    - torchvision==0.17.0
    - mlflow>=1.0
    - imblearn